### ISSUE TITLE
Swap test

### ISSUE THREAD

**Issue by Baxi-codes** [sahana3131/ML4SCI#1]
Hi there,
I noticed that you recently implemented the swap test in your repo for the QMLHEP task 1 for GSoC, but I think the implementation is incorrect, or at least different than what I've read and seen most people doing. You usually do a swap test to know the fidelity of two states.
Apologies if I am wrong.

![Quantum-swap-test-circuit-correct](https://user-images.githubusercontent.com/46259792/227954595-01e1685e-cf53-4205-a04a-e6b355ccc3c1.png)

Also, I was curious how many tasks you are planning on submitting for the QMLHEP tasks for GSoC and when you are planning on submitting them. I have completed tasks 1, 2, 3, and 7, and I'm currently working on the remaining tasks. It would be great to know where you're at in the process as well.

PS. Sorry for opening an issue, I couldn't think of any other channel to communicate

**Comment by sahana3131** [comment]
the swap gate and swap test are two different concepts in quantum computing. The swap gate is a quantum gate that swaps the quantum states of two qubits in a quantum circuit, while the swap test is a quantum algorithm that compares the similarity of two quantum states.task 1 is about swap gates..
circuit.append(cirq.SWAP(qubits[0], qubits[4]))  swaps the quantum states of two qubits in a quantum circuit represented by the variable "circuit".
the one that you are asking is about swap test which is not a part of task1.

**Comment by Baxi-codes** [comment]
Perform a swap test between the states of the first and second qubit |q1 q2> and the third and fourth qubit |q3 q4>
This one
